name: release-build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get the version to publish
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login in GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "Building and pushing version: ${{ env.VERSION }}"
          docker build -t ghcr.io/${{ github.repository }}/my-image:${{ env.VERSION }} .
          docker tag ghcr.io/${{ github.repository }}/my-image:${{ env.VERSION }} ghcr.io/${{ github.repository }}/my-image:latest
          docker push ghcr.io/${{ github.repository }}/my-image:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}/my-image:latest
